In [7]:
import numpy as np
from scipy import signal
from msicpe.sas import pplane, zplane, pdiagrammes, zdiagrammes
import plotly.express as px
import pandas as pd
from systems_tp import systems

In [ ]:
# Système analogique (à temps continu)
b_a, a_a = np.array([10000]), np.array([1., 26.13, 341.42, 2613.13, 10000])
system_a = signal.TransferFunction(b_a, a_a) 
# Donne les coefficients au numérateur et au dénumérateur du système
print(system_a.to_tf())
# Donne les matrices de réprésentation d'état du système
print(system_a.to_ss())
# Donne la forme factorisée (zéros, pôles, gain)
print(system_a.to_zpk())
# Tracé du diagramme Pôles-Zéros pour analyse de la stabilité
pplane(system_a)
# Tracés des diagrammes de Bode, Black-Nichols et Nyquist pour l'analyse fréquentielle
pdiagrammes(system_a)
# Tracé de la réponse indicielle
t_step, y_step = signal.step(system_a)
fig = px.line(x=t_step,y=y_step,
    labels={
        "x": "Temps (s)",
        "y": "Amplitude"
    },
    title="Réponse indicielle"
)
fig.update_layout(
    width=500,
    height=500
)
fig.show()

TransferFunctionContinuous(
array([10000.]),
array([1.00000e+00, 2.61300e+01, 3.41420e+02, 2.61313e+03, 1.00000e+04]),
dt: None
)
StateSpaceContinuous(
array([[-2.61300e+01, -3.41420e+02, -2.61313e+03, -1.00000e+04],
       [ 1.00000e+00,  0.00000e+00,  0.00000e+00,  0.00000e+00],
       [ 0.00000e+00,  1.00000e+00,  0.00000e+00,  0.00000e+00],
       [ 0.00000e+00,  0.00000e+00,  1.00000e+00,  0.00000e+00]]),
array([[1.],
       [0.],
       [0.],
       [0.]]),
array([[    0.,     0.,     0., 10000.]]),
array([[0.]]),
dt: None
)
ZerosPolesGainContinuous(
array([], dtype=float64),
array([-3.82721691+9.23928695j, -3.82721691-9.23928695j,
       -9.23778309+3.82770851j, -9.23778309-3.82770851j]),
np.float64(10000.0),
dt: None
)


In [ ]:
# Système numérique (à temps discret)
b_n, a_n = np.array([0.018, 0.070, 0.106, 0.070, 0.018]), np.array([1.0, -1.609,  1.315, -0.504,  0.080])
system_n = signal.TransferFunction(b_n, a_n, dt=0.1)
# Donne les coefficients au numérateur et au dénumérateur du système
print(system_n.to_tf())
# Donne les matrices de réprésentation d'état du système
print(system_n.to_ss())
# Donne la forme factorisée (zéros, pôles, gain)
print(system_n.to_zpk())
# Tracé du diagramme Pôles-Zéros dans le plan complexe Z
zplane(system_n)
# Tracés des diagrammes fréquentiels discrets
zdiagrammes(system_n)
# Tracé de la réponse indicielle discrète
t, y = signal.dstep(system_n)
y = np.squeeze(y)
fig = px.scatter(
    x=t,
    y=y,
    labels={
        "x": "n (échantillons)",
        "y": "Amplitude"
    },
    title="Réponse indicielle discrète"
)

fig.update_layout(
    width=500,
    height=500
)

fig.show()

TransferFunctionDiscrete(
array([0.018, 0.07 , 0.106, 0.07 , 0.018]),
array([ 1.   , -1.609,  1.315, -0.504,  0.08 ]),
dt: 0.1
)
StateSpaceDiscrete(
array([[ 1.609, -1.315,  0.504, -0.08 ],
       [ 1.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ]]),
array([[1.],
       [0.],
       [0.],
       [0.]]),
array([[0.098962, 0.08233 , 0.079072, 0.01656 ]]),
array([[0.018]]),
dt: 0.1
)
ZerosPolesGainDiscrete(
array([-1.32439598+0.61800556j, -1.32439598-0.61800556j,
       -0.62004846+0.28933446j, -0.62004846-0.28933446j]),
array([0.46029706+0.56441632j, 0.46029706-0.56441632j,
       0.34420294+0.17984093j, 0.34420294-0.17984093j]),
np.float64(0.018),
dt: 0.1
)


In [44]:
S = systems["C4"]
A = S["A"]
B = S["B"]
C = S["C"]
D = S["D"]

# Création du système continu
sys_C4 = signal.StateSpace(A, B, C, D)
sys_C4_tf = sys_C4.to_tf()

# Donne les coefficients au numérateur et au dénumérateur du système
print(sys_C4.to_tf())
# Donne les matrices de réprésentation d'état du système
print(sys_C4.to_ss())
# Donne la forme factorisée (zéros, pôles, gain)
print(sys_C4.to_zpk())

# Tracé du diagramme Pôles-Zéros pour analyse de la stabilité
pplane(sys_C4)
# Tracés des diagrammes de Bode, Black-Nichols et Nyquist pour l'analyse fréquentielle
pdiagrammes(sys_C4)
# Tracé de la réponse indicielle
t_step, y_step = signal.step(sys_C4)
fig = px.line(x=t_step,y=y_step,
    labels={
        "x": "Temps (s)",
        "y": "Amplitude"
    },
    title="Réponse indicielle"
)
fig.update_layout(
    width=500,
    height=500
)
fig.show()

TransferFunctionContinuous(
array([39.4784176]),
array([ 1.        , 18.84955592, 39.4784176 ]),
dt: None
)
StateSpaceContinuous(
array([[  0.        ,   1.        ],
       [-39.4784176 , -18.84955592]]),
array([[ 0.       ],
       [39.4784176]]),
array([[1, 0]]),
array([[0]]),
dt: None
)
ZerosPolesGainContinuous(
array([], dtype=float64),
array([-16.44959269,  -2.39996323]),
np.float64(39.47841760435745),
dt: None
)


c:\python_envs\env_msi\Lib\site-packages\scipy\signal\_ltisys.py:599: BadCoefficients:

Badly conditioned filter coefficients (numerator): the results may be meaningless

c:\python_envs\env_msi\Lib\site-packages\scipy\signal\_filter_design.py:1125: BadCoefficients:

Badly conditioned filter coefficients (numerator): the results may be meaningless

