In [1]:
import numpy as np
import numpy.linalg as alg

## Question 1

In [4]:
A = np.array([
    [1, -2, 3, 1],
    [2, 5, -1, 3],
    [4, 1, 0, 2],
    [0, -2, 3, 1]
])

print("1. Matrice A")
print(A, '\n')

1. Matrice A
[[ 1 -2  3  1]
 [ 2  5 -1  3]
 [ 4  1  0  2]
 [ 0 -2  3  1]] 



## Question 2

In [5]:
print("2. Slicing")
print("3ème colonne :")
print(A[:, 2], '\n')

print("4ème ligne :")
print(A[3, :], '\n')

2. Slicing
3ème colonne :
[ 3 -1  0  3] 

4ème ligne :
[ 0 -2  3  1] 



## Question 3

In [6]:
A[:, 2] = 1 
print("3. Matrice A modifiée")
print(A, '\n')

3. Matrice A modifiée
[[ 1 -2  1  1]
 [ 2  5  1  3]
 [ 4  1  1  2]
 [ 0 -2  1  1]] 



## Question 4

In [10]:
det_A = alg.det(A)
trace_A = alg.trace(A)

print("4. Trace et Déterminant")
print(f"Déterminant : {det_A}")
print(f"Trace : {trace_A}\n")

4. Trace et Déterminant
Déterminant : -0.9999999999999938
Trace : 8



## Question 5

In [9]:
b = np.array([[1], [2], [-1], [3]])
A_inv = alg.inv(A)
x = A_inv @ b

print("5. Résolution Ax=b et Inverse")
print("Solution x :\n", x)
print("Inverse de A :\n", A_inv, '\n')

5. Résolution Ax=b et Inverse
Solution x :
 [[ -2.]
 [ -5.]
 [-26.]
 [ 19.]]
Inverse de A :
 [[ 1.00000000e+00  9.43689571e-16 -1.99840144e-15 -1.00000000e+00]
 [ 6.00000000e+00  1.00000000e+00 -2.00000000e+00 -5.00000000e+00]
 [ 3.40000000e+01  5.00000000e+00 -1.10000000e+01 -2.70000000e+01]
 [-2.20000000e+01 -3.00000000e+00  7.00000000e+00  1.80000000e+01]] 



## Question 6